"""creating the budget table

Revision ID: f6d490450eaf
Revises: 4f6a0d26ba17
Create Date: 2026-03-16 10:52:02.570304

"""
from typing import Sequence, Union
import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f6d490450eaf'
down_revision: Union[str, Sequence[str], None] = '4f6a0d26ba17'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('budget',
    sa.Column('budget_id', sa.Uuid(), nullable=False),
    sa.Column('item_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('item_type', sa.JSON(), nullable=True),
    sa.Column('purchase_date', sa.DateTime(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('budget_id')
    )
    op.create_index(op.f('ix_budget_description'), 'budget', ['description'], unique=False)
    op.create_index(op.f('ix_budget_item_name'), 'budget', ['item_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_budget_item_name'), table_name='budget')
    op.drop_index(op.f('ix_budget_description'), table_name='budget')
    op.drop_table('budget')
    # ### end Alembic commands ###
